# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306

  adminer:
    image: adminer
      - 8080:8080
