const exportFormat = {
  account: {
    fileName: "Danh_sach_tai_khoan.xlsx",
    tableHeading: "DANH SÁCH TÀI KHOẢN",
    columns: [
      {
        name: "STT",
        caption: "STT",
        width: 10,
        align: "left",
        type: "text",
      },
      {
        name: "AccountNumber",
        caption: "Số tài khoản",
        width: 20,
        align: "left",
        type: "text",
      },
      {
        name: "AccountNameVi",
        caption: "Tên tài khoản",
        width: 30,
        align: "left",
        type: "text",
      },
      {
        name: "CategoryKindName",
        caption: "Tính chất",
        width: 20,
        align: "left",
        type: "text",
      },
      {
        name: "AccountNameEn",
        caption: "Tên tiếng Anh",
        width: 30,
        align: "left",
        type: "text",
      },
      {
        name: "Description",
        caption: "Diễn giải",
        width: 40,
        align: "left",
        type: "text",
      },
      {
        name: "UsingStatusName",
        caption: "Trạng thái",
        width: 20,
        align: "left",
        type: "text",
      },
    ],
    keySearch: "",
  },
  customer: {
    fileName: "Danh_sach_khach_hang.xlsx",
    tableHeading: "DANH SÁCH KHÁCH HÀNG",
    columns: [
      {
        name: "STT",
        caption: "STT",
        width: 10,
        align: "left",
        type: "text",
      },
      {
        name: "CustomerCode",
        caption: "Mã khách hàng",
        width: 20,
        align: "left",
        type: "text",
      },
      {
        name: "CustomerFullName",
        caption: "Tên khách hàng",
        width: 40,
        align: "left",
        type: "text",
      },
      {
        name: "Address",
        caption: "Địa chỉ",
        width: 40,
        align: "left",
        type: "text",
      },
      {
        name: "PhoneNumber",
        caption: "Số điện thoại",
        width: 20,
        align: "left",
        type: "text",
      },
      {
        name: "IdentityNumber",
        caption: "Số CMND",
        width: 20,
        align: "left",
        type: "text",
      },
    ],
    keySearch: "",
  },
  receipt: {
    fileName: "Thu_chi_tien_mat.xlsx",
    tableHeading: "THU CHI TIỀN MẶT",
    columns: [
      {
        name: "STT",
        caption: "STT",
        width: 10,
        align: "left",
        type: "text",
      },
      {
        name: "PostedDate",
        caption: "Ngày hạch toán",
        width: 20,
        align: "center",
        type: "date",
      },
      {
        name: "ReceiptDate",
        caption: "Ngày chứng từ",
        width: 20,
        align: "center",
        type: "date",
      },
      {
        name: "ReceiptNo",
        caption: "Số chứng từ",
        width: 20,
        align: "left",
        type: "text",
      },
      {
        name: "Reason",
        caption: "Diễn giải",
        width: 40,
        align: "left",
        type: "text",
      },
      {
        name: "TotalAmount",
        caption: "Số tiền",
        width: 20,
        align: "right",
        type: "number",
      },
      {
        name: "CustomerName",
        caption: "Đối tượng",
        width: 40,
        align: "left",
        type: "text",
      },
      {
        name: "CustomerCode",
        caption: "Mã đối tượng",
        width: 20,
        align: "left",
        type: "text",
      },
      {
        name: "CustomerAddress",
        caption: "Địa chỉ",
        width: 40,
        align: "left",
        type: "text",
      },
    ],
    keySearch: "",
  },
};

export default exportFormat;
