const MSResource = {
  VN: {
    UserName: "Lê Đức Tiệp",
    CompanyName: "CÔNG TY TNHH SẢN XUẤT - THƯƠNG MẠI - DỊCH VỤ QUI PHÚC",
    Error: {
      UnknownError: "Có lỗi xảy ra, vui lòng liên hệ MS để được hỗ trợ.",
      FullNameRequired: "Tên không được để trống",
      Required: "Không được để trống",
      CodeDuplicated: "Mã đã bị sử dụng",
      CodeExisted: "Mã đã tồn tại",
      IncorrectFormat: "Không đúng định dạng",
      DateOfBirthTime: "Ngày không chính xác",
      IdentityDateTime: "Ngày không chính xác",
      NoLongerThan: "{0} không được dài quá {1} kí tự",
      AccountCodeError: "Số tài khoản phải bắt đầu bằng tài khoản tổng hợp",
      DuplicatedBankAccount: "Số tài khoản không được trùng",
    },
    Placeholder: {
      InputSearch: "Nhập theo mã, họ tên",
    },
    Header: {
      Employee: "Nhân viên",
    },
    Nav: {
      Accountant: "Kế toán",
      Overview: "Tổng quan",
      Cash: "Tiền mặt",
      Deposits: "Tiền gửi",
      Purchase: "Mua hàng",
      Sell: "Bán hàng",
      BillManagement: "Quản lý hóa đơn",
      Warehouse: "Kho",
      ServiceTools: "Công cụ dịch vụ",
      FixedAssets: "Tài sản cố định",
      Tax: "Thuế",
      Price: "Giá thành",
      Synthetic: "Tổng hợp",
      Budget: "Ngân sách",
      Report: "Báo cáo",
      FinancialAnalysis: "Phân tích tài chính",
      Account: "Tài khoản",
      Edit: "Sửa",
      Collapse: "Thu gọn",
      Category: "Danh mục",
    },
    Selection: {
      Selected: "Đã chọn",
      UnSelect: "Bỏ chọn",
    },
    DateTime: {
      Sunday: "CN",
      Monday: "T2",
      Tuesday: "T3",
      Wednesday: "T4",
      Thursday: "T5",
      Friday: "T6",
      Saturday: "T7",
      Today: "Hôm nay",
      Month: "Tháng",
    },
    Button: {
      AddEmployee: "Thêm mới nhân viên",
      ReloadList: "Tải lại",
      ExportList: "Xuất ra excel",
      Search: "Tìm kiếm",
      Cancel: "Hủy",
      Close: "Đóng",
      SaveAndAdd: "Cất và thêm",
      Edit: "Sửa",
      Save: "Cất",
      No: "Không",
      Delete: "Xóa",
      Accept: "Đồng ý",
      ChangeLanguage: "Đổi ngôn ngữ",
      Utilities: "Tiện ích",
      Add: "Thêm",
      Setting: "Cài đặt",
      View: "Xem",
    },
    NoticeType: {
      Success: "Thành công!",
      Error: "Lỗi!",
      Warning: "Cảnh báo!",
      Information: "Thông tin!",
    },
    EmployeeExport: {
      FileName: "Danh_sach_nhan_vien.xlsx",
    },
    ReceiptExport: {
      FileName: "Danh_sach_phieu_thu.xlsx",
    },
    AccountExport: {
      FileName: "Danh_sach_tai_khoan.xlsx",
    },
    CustomerExport: {
      FileName: "Danh_sach_khach_hang.xlsx",
    },
    MenuFeatures: {
      View: "Xem",
      Replication: "Nhân bản",
      Delete: "Xóa",
      StopUsing: "Ngừng sử dụng",
    },
    Dialog: {
      DefaultTitle: "Thông báo",
      DeleteRecord: "Xóa bản ghi",
      ErrorTitle: "Lỗi",
      SaveChanges: "Lưu thay đổi",
      FeatureNotSupported: "Tính năng này đang được phát triển",
    },
    FormTitle: {
      Add: "Thêm thông tin nhân viên",
      Edit: "Sửa thông tin nhân viên",
    },
    DeleteAlert: "Bạn có chắc chắn muốn xóa <{0}> {1}?",
    DeleteSelectedAlert: "Bạn có chắc chắn muốn xóa {0} bản ghi?",
    FormChangedAlert: "Dữ liệu đã bị thay đổi. Bạn có muốn cất không?",
    CustomerList: {
      CustomerCode: "Mã khách hàng",
      FullName: "Tên khách hàng",
      Address: "Địa chỉ",
      PhoneNumber: "Số điện thoại",
      PhoneNumberShort: "SĐT",
      IdentityNumber: "Số chứng minh nhân dân",
      IdentityNumberShort: "Số cmnd",
      Feature: "Chức năng",
      TotalNumberOfRecordsIs: "Tổng số: {0} bản ghi",
      NumberOfRecordOutOfPageIs: "Số bản ghi/trang: ",
      FromXToYRecords: "{0} - {1} bản ghi",
    },
    ReceiptList: {
      ReceiptCode: "Mã khách hàng",
      FullName: "Tên khách hàng",
      Address: "Địa chỉ",
      PhoneNumber: "Số điện thoại",
      PhoneNumberShort: "SĐT",
      IdentityNumber: "Số chứng minh nhân dân",
      IdentityNumberShort: "Số cmnd",
      Feature: "Chức năng",
      TotalNumberOfRecordsIs: "Tổng số: {0} bản ghi",
      NumberOfRecordOutOfPageIs: "Số bản ghi/trang: ",
      FromXToYRecords: "{0} - {1} bản ghi",
    },
    AccountList: {
      AccountCode: "Số tài khoản",
      FullName: "Tên tài khoản",
      NameVi: "Tên tài khoản",
      AccountProperty: "Tính chất",
      NameEn: "Tên tiếng anh",
      Note: "Diễn giải",
      Address: "Địa chỉ",
      PhoneNumber: "Số điện thoại",
      PhoneNumberShort: "SĐT",
      IdentityNumber: "Số chứng minh nhân dân",
      IdentityNumberShort: "Số cmnd",
      Feature: "Chức năng",
      TotalNumberOfRecordsIs: "Tổng số: {0} bản ghi",
      NumberOfRecordOutOfPageIs: "Số bản ghi/trang: ",
      FromXToYRecords: "{0} - {1} bản ghi",
      Expand: "Mở rộng",
      Collapse: "Thu gọn",
    },
    Cash: {
      FundInventory: "Kiểm Kê quỹ",
      CollectMoney: "Thu tiền",
      CashBusiness: "Nghiệp vụ tiền mặt",
      Pay: "Chi tiền",
      Report: "Báo cáo",
      DailyCashBalanceStatisticsTable: "Bảng thống kê số dư tiền hằng ngày",
      CashFlow: "Dòng tiền",
      CashCollectionLogNumber: "Số nhật ký thu tiền",
      DetailedAccountingNumberOfCashFund: "Số kế toán chi tiết quỹ tiền mặt",
      PaymentDiaryNumber: "Số nhật ký chi tiền",
      AllReports: "Tất cả báo cáo",
      UnRecorded: "Bỏ ghi",
      FastEdit: "Sửa nhanh",
      SetRecorded: "Ghi sổ",
      DragDropFilesHereOrClickHere: "Kéo/thả tệp vào đây hoặc bấm vào đây",
      MaximumCapacity: "Dung lượng tối đa {0}",
      Attach: "Đính kèm",
      DeleteAllLines: "Xóa hết dòng",
      AddLine: "Thêm dòng",
      Explain: "Diễn giải",
      DebtAccount: "TK nợ",
      CreditAccount: "TK có",
      Object: "Đối tượng",
      ObjectName: "Tên đối tượng",
      AmountOfMoney: "Số tiền",
      Accounting: "Hạch toán",
      TotalMoney: "Tổng tiền",
      Rejoin: "Kèm theo",
      Reason: "Lý do nộp",
      Amount: "Số lượng",
      OriginalDocuments: "chứng từ gốc",
      Employee: "Nhân viên",
      Payer: "Người nộp",
      CustomerName: "Tên khách hàng",
      TaxCode: "Mã số thuế",
      Address: "Địa chỉ",
      PhoneNumber: "Số điện thoại",
      CustomerCode: "Mã khách hàng",
      CollectMoneyFromCustomers: "Thu tiền khách hàng",
      EmployeeApplicationRefund: "Thu hoàn ứng nhân viên",
      WithdrawDepositToFundEntry: "Rút tiền gửi về nhập quỹ",
      OtherAutumn: "Thu khác",
      Receipts: "Phiếu thu",
      Procedure: "Quy trình",
      CollectAndSpendMoney: "Thu, chi tiền",
      TotalRevenueFromTheBeginningOfTheYearToThePresent:
        "Tổng thu đầu năm đến hiện tại",
      TotalExpenditureAtTheBeginningOfTheYearToPresent:
        "Tổng chi đầu năm đến hiện tại",
      CurrentFundBalance: "Tồn quỹ hiện tại",
      Selected: "Đã chọn",
      UnSelect: "Bỏ chọn",
    },
    EmployeeList: {
      EmployeeCode: "Mã nhân viên",
      FullName: "Tên nhân viên",
      Gender: "Giới tính",
      PhoneNumber: "Số điện thoại",
      DateOfBirth: "Ngày sinh",
      IdentityNumberShort: "Số cmnd",
      IdentityNumber: "Số chứng minh nhân dân",
      PositionName: "Chức danh",
      DepartmentName: "Tên đơn vị",
      BankAccountNumber: "Số tài khoản",
      BankAccountNumberShort: "Số tài khoản",
      NameOfBank: "Tên ngân hàng",
      BankAccountBranchShort: "Chi nhánh tk ngân hàng",
      BankAccountBranch: "Chi nhánh tài khoản ngân hàng",
      Function: "Chức năng",
      TotalNumberOfRecordsIs: "Tổng số: {0} bản ghi",
      NumberOfRecordOutOfPageIs: "Số bản ghi/trang: ",
      FromXToYRecords: "{0} - {1} bản ghi",
    },
    EmployeeForm: {
      EmployeeCode: "Mã",
      FullName: "Tên",
      Department: "Đơn vị",
      Position: "Chức danh",
      DayOfBirth: "Ngày sinh",
      Gender: "Giới tính",
      IdentityNumberShort: "Số CMND",
      IdentityNumber: "Số chứng minh nhân dân",
      IdentityDate: "Ngày cấp",
      IdentityPlace: "Nơi cấp",
      Address: "Địa chỉ",
      PhoneNumberShort: "ĐT di động",
      PhoneNumber: "Điện thoại di động",
      LandlinePhoneShort: "ĐT cố định",
      LandlinePhone: "Điện thoại cố định",
      Email: "Email",
      BankAccountNumber: "Tài khoản ngân hàng",
      NameOfBank: "Tên ngân hàng",
      BankAccountBranch: "Chi nhánh",
    },
    AccountForm: {
      AccountCode: "Số tài khoản",
      NameVi: "Tên tài khoản",
      NameEn: "Tên tiếng anh",
      Note: "Diễn giải",
      AccountSynthetic: "Tài khoản tổng hợp",
      AccountProperty: "Tính chất",
      HasForeignCurrencyAccounting: "Có hạch toán ngoại tệ",
      ObjectType: "Đối tượng",
      FollowBy: "Theo dõi chi tiết theo",
      CostAggregationObject: "Đối thượng THCP",
      TheOrder: "Đơn đặt hàng",
      PurchaseContract: "Hợp đồng mua",
      Unit: "Đơn vị",
      BankAccount: "Tài khoản ngân hàng",
      Construction: "Công trình",
      ContractOfSale: "Hợp đồng bán",
      ExpenseItem: "Khoản mục CP",
      StatisticalCode: "Mã thống kê",
    },
    AccountHome: {
      AccountList: "Danh sách tài khoản",
      AllCategory: "Tất cả danh mục",
    },
    ReceiptForm: {
      ReceiptCode: "Số phiếu thu",
      ReceiptType: "Loại phiếu thu",
      CustomerName: "Tên khách hàng",
      Payer: "Người nộp",
      Address: "Địa chỉ",
      Reason: "Lý do nộp",
      Amount: "Số lượng kèm theo",
      AccountingDate: "Ngày hạch toán",
      ReceiptDate: "Ngày phiếu thu",
    },
    CustomerForm: {
      TaxCode: "Mã số thuế",
      CustomerCode: "Mã khách hàng",
      FullName: "Tên",
      Address: "Địa chỉ",
      PhoneNumber: "Số điện thoại",
      Website: "Website",
      IdentityNumber: "Số chứng minh nhân dân",
      IdentityPlace: "Nơi cấp chứng minh nhân dân",
      CustomerName: "Tên khách hàng",
      Phone: "Điện thoại",
      CustomerGroup: "Nhóm khách hàng",
      CustomerGroupCode: "Mã nhóm khách hàng",
      CustomerGroupName: "Tên nhóm khách hàng",
      SalesAgent: "Nhân viên bán hàng",
      HumanContact: "Người liên hệ",
      Vocative: "Xưng hô",
      FirstAndLastName: "Họ và tên",
      ElectronicInvoiceRecipients: "Người nhận hóa đơn điện tử",
      LegalRepresentative: "Đại diện theo pháp luật",
      EmailPlaceHolder: 'Email (Ngăn cách nhiều email bởi dấu chấm phẩy ";")',
      TermsOfPayment: "Điều khoản thanh toán",
      TermsOfPaymentName: "Tên điều khoản thanh toán",
      TermsOfPaymentCode: "Mã điều khoản thanh toán",
      MaxDaysOwed: "Số ngày được nợ",
      MaxAmountOfDebt: "Số nợ tối đa",
      AccountCollect: "Tài khoản công nợ phải thu",
      AccountCode: "Số tài khoản",
      AccountName: "Tên tài khoản",
      BankName: "Tên ngân hàng",
      Brach: "Chi nhánh",
      BanksCity: "Tỉnh/TP của nhân hàng",
      Location: "Vị trí địa lý",
      Nation: "Quốc gia",
      City: "Tỉnh/Thành phố",
      District: "Quận/Huyện",
      Commune: "Xã/Phường",
      DeliveryAddress: "Địa chỉ giao hàng",
      SameAsCustomerAddress: "Giống địa chỉ khách hàng",
      Note: "Ghi chú",
      ContactInfor: "Thông tin liên hệ",
      IdentityTitle: "Thông tin CMND/Thẻ căn cước",
      IdentityPlaceholder: "Số CMND/Thẻ căn cước",
    },
    CustomerHome: {
      CustomerList: "Danh sách khách hàng",
      AllCategory: "Tất cả danh mục",
    },
    Notice: {
      Post: {
        Success: "Thêm mới thành công",
        Error: "Thêm mới thất bại",
      },
      Put: {
        Success: "Sửa thành công",
        Error: "Sửa thất bại",
      },
      Delete: {
        Success: "Xóa thành công",
        ManySuccess: "Xóa thành công {0} bản ghi",
        Error: "Xóa thất bại",
      },
      BookKeeping: {
        Success: "Ghi sổ thành công",
        Error: "Ghi sổ thất bại",
      },
      UnBookKeeping: {
        Success: "Bỏ ghi sổ thành công",
        Error: "Bỏ ghi sổ thất bại",
      },
    },

    Gender: {
      Male: "Nam",
      Female: "Nữ",
      Other: "Khác",
      OtherGender: "(Chưa xác định)",
    },
    NoData: "Không có dữ liệu",
  },
  EN: {
    UserName: "Lê Đức Tiệp",
    CompanyName: "PRODUCTION COMPANY - COMMERCE - QUI PHUC SERVICES",
    Error: {
      UnknownError: "An error occurred, please contact MS for support.",
      FullNameRequired: "Name cannot be blank",
      EmployeeCodeDuplicated: "Code has been used",
      EmployeeCodeExisted: "Code already exists",
      IncorrectFormat: "Incorrect format",
      DateOfBirthTime: "Incorrect date",
      IdentityDateTime: "Incorrect date",
      NoLongerThan: "{0} must not be longer than {1} character",
    },
    Placeholder: {
      InputSearch: "Enter by code, employee name",
    },
    Header: {
      Employee: "Employee",
    },
    Nav: {
      Accountant: "Accountant",
      Overview: "Overview",
      Cash: "Cash",
      Deposits: "Deposits",
      Purchase: "Purchase",
      Sell: "Sell",
      BillManagement: "Bill management",
      Warehouse: "Warehouse",
      ServiceTools: "Service Tools",
      FixedAssets: "Fixed assets",
      Tax: "Tax",
      Price: "Price",
      Synthetic: "Synthetic",
      Budget: "Budget",
      Report: "Report",
      FinancialAnalysis: "Financial analysis",
      Account: "Account",
      Edit: "Edit",
      Collapse: "Collapse",
    },
    Selection: {
      Selected: "Selected",
      UnSelect: "UnSelect",
    },
    DateTime: {
      Sunday: "Sun",
      Monday: "Mon",
      Tuesday: "Tue",
      Wednesday: "Wed",
      Thursday: "Thu",
      Friday: "Fri",
      Saturday: "Sat",
      Today: "Today",
      Month: "Month",
    },
    Button: {
      AddEmployee: "Add new employee",
      ReloadList: "Reload",
      ExportEmployeeList: "Export to excel",
      Search: "Search",
      Edit: "Edit",
      Cancel: "Cancel",
      Close: "Close",
      SaveAndAdd: "Save and add",
      Save: "Save",
      No: "No",
      Delete: "Delete",
      Accept: "Accept",
      ChangeLanguage: "Change language",
    },
    NoticeType: {
      Success: "Success!",
      Error: "Error!",
      Warning: "Warning!",
      Information: "Information!",
    },
    MenuFeatures: {
      Replication: "Replication",
      Delete: "Delete",
      StopUsing: "Stop using",
    },
    FormTitle: {
      Add: "Add employee information",
      Edit: "Edit employee information",
    },
    DeleteAlert: "Are you sure you want to delete <{0}> {1}?",
    DeleteSelectedAlert: "Are you sure you want to delete {0} records?",
    FormChangedAlert: "The data has been changed. Do you want to save it?",
    EmployeeList: {
      EmployeeCode: "Employee code",
      FullName: "Full name",
      Gender: "Gender",
      DateOfBirth: "Date of birth",
      IdentityNumberShort: "ID number",
      IdentityNumber: "Identity number",
      PositionName: "Position",
      DepartmentName: "Department",
      BankAccountNumber: "Bank account number",
      BankAccountNumberShort: "BAN",
      NameOfBank: "Name of bank",
      BankAccountBranchShort: "Bank account branch",
      BankAccountBranch: "Bank account branch",
      Function: "Feature",
      TotalNumberOfRecordsIs: "Total: {0} records",
      NumberOfRecordOutOfPageIs: "Number of records/page: ",
      FromXToYRecords: "{0} - {1} records",
    },
    EmployeeForm: {
      EmployeeCode: "Code",
      FullName: "Name",
      Department: "Department",
      Position: "Position",
      DayOfBirth: "Day of birth",
      Gender: "Gender",
      IdentityNumberShort: "ID number",
      IdentityNumber: "Identity card number",
      IdentityDate: "Identity date",
      IdentityPlace: "Identity place",
      Address: "Address",
      PhoneNumberShort: "Phone number",
      PhoneNumber: "Phone number",
      LandlinePhoneShort: "Landline number",
      LandlinePhone: "Landline number",
      Email: "Email",
      BankAccountNumber: "Bank account number",
      NameOfBank: "Name of bank",
      BankAccountBranch: "Bank account branch",
    },
    Notice: {
      Post: {
        Success: "Successfully added",
        Error: "Added failure",
      },
      Put: {
        Success: "Successful fix",
        Error: "Fix failure",
      },
      Delete: {
        Success: "Successful delete",
        ManySuccess: "Successful delete {0} records",
        Error: "Delete failure",
      },
    },
    Gender: {
      Male: "Male",
      Female: "Female",
      Other: "Other",
      OtherGender: "(Unknown)",
    },
    NoData: "No data",
  },
};

export default MSResource;
